// File: SketchStyleKit.swift
//
// NOTE:
// File automatically generated by "SketchStyleKitExport.php" tool.
// Any modification will lost on next export!

import UIKit

func UIColorFromRGB(hex: Int) -> UIColor {
    let R = CGFloat((hex & 0xFF0000) >> 16) / 255.0
    let G = CGFloat((hex & 0xFF00) >> 8) / 255.0
    let B = CGFloat(hex & 0xFF) / 255.0
    return UIColor(red: R, green: G, blue: B, alpha: 1.0)
}

public class SketchStyleKit {
    
    // LayerStyle: "Control: Segmented Fill"
    public class controlSegmentedFill {
        public class var fillColor: UIColor {
            return UIColorFromRGB(0x44D3C2)
        }
    }

    // LayerStyle: "Control: Segmented Stroke"
    public class controlSegmentedStroke {
        public class var borderColor: UIColor {
            return UIColorFromRGB(0x44D3C2)
        }
    }

    // LayerStyle: "Icon: Background"
    public class iconBackground {
        public class var fillColor: UIColor {
            return UIColorFromRGB(0x44D3C2)
        }
    }

    // LayerStyle: "Palette: Color 1 Fill"
    public class paletteColor1Fill {
        public class var fillColor: UIColor {
            return UIColorFromRGB(0xEF1945)
        }
    }

    // LayerStyle: "Palette: Color 2 Fill"
    public class paletteColor2Fill {
        public class var fillColor: UIColor {
            return UIColorFromRGB(0xF39600)
        }
    }

    // LayerStyle: "Palette: Color 3 Fill"
    public class paletteColor3Fill {
        public class var fillColor: UIColor {
            return UIColorFromRGB(0xE9F1DE)
        }
    }

    // LayerStyle: "Palette: Color 4 Fill"
    public class paletteColor4Fill {
        public class var fillColor: UIColor {
            return UIColorFromRGB(0x44D3C2)
        }
    }

    // LayerStyle: "Palette: Color 5 Fill"
    public class paletteColor5Fill {
        public class var fillColor: UIColor {
            return UIColorFromRGB(0x2B8FB3)
        }
    }

    // LayerStyle: "ProfileView: Avatar Outline"
    public class profileViewAvatarOutline {
        public class var borderColor: UIColor {
            return UIColorFromRGB(0xFFFFFF)
        }
    }

    // LayerStyle: "UI: Popup"
    public class uiPopup {
        public class var fillColor: UIColor {
            return UIColor(red: 68 / 255.0, green: 211 / 255.0, blue: 194 / 255.0, alpha: 0.89)
        }
    }

    // LayerStyle: "UI: Selected TableViewCell Background"
    public class uiSelectedTableViewCellBackground {
        public class var fillColor: UIColor {
            return UIColorFromRGB(0xF2F2F2)
        }
    }

    // LayerStyle: "UI: TableView Background"
    public class uiTableViewBackground {
        public class var fillColor: UIColor {
            return UIColorFromRGB(0xF9F9F9)
        }
    }

    // LayerTextStyle: "Cell: Friend Name"
    public class cellFriendName {
        public class var font: UIFont {
            return UIFont(name: "OpenSans", size: 30 / 2.000000)!
        }
        public class var fillColor: UIColor {
            return UIColorFromRGB(0x343434)
        }
    }

    // LayerTextStyle: "Control: Segment Title"
    public class controlSegmentTitle {
        public class var font: UIFont {
            return UIFont(name: "OpenSans", size: 24 / 2.000000)!
        }
        public class var fillColor: UIColor {
            return UIColorFromRGB(0xFFFFFF)
        }
    }

    // LayerTextStyle: "Post: Date"
    public class postDate {
        public class var font: UIFont {
            return UIFont(name: "OpenSans", size: 22 / 2.000000)!
        }
        public class var fillColor: UIColor {
            return UIColorFromRGB(0x45B4A7)
        }
    }

    // LayerTextStyle: "Post: Link Subtitle"
    public class postLinkSubtitle {
        public class var font: UIFont {
            return UIFont(name: "OpenSans-Light", size: 24 / 2.000000)!
        }
        public class var fillColor: UIColor {
            return UIColorFromRGB(0x2B8FB3)
        }
    }

    // LayerTextStyle: "Post: Link Title"
    public class postLinkTitle {
        public class var font: UIFont {
            return UIFont(name: "OpenSans", size: 24 / 2.000000)!
        }
        public class var textColor: UIColor {
            return UIColor(red: 0.484455, green: 0.484455, blue: 0.484455, alpha: 1.000000)
        }
    }

    // LayerTextStyle: "Post: Title"
    public class postTitle {
        public class var font: UIFont {
            return UIFont(name: "OpenSans", size: 26 / 2.000000)!
        }
        public class var fillColor: UIColor {
            return UIColorFromRGB(0x424242)
        }
    }

    // LayerTextStyle: "Profile: Location"
    public class profileLocation {
        public class var font: UIFont {
            return UIFont(name: "OpenSans", size: 28 / 2.000000)!
        }
        public class var fillColor: UIColor {
            return UIColorFromRGB(0xFFFFFF)
        }
    }

    // LayerTextStyle: "Profile: Title"
    public class profileTitle {
        public class var font: UIFont {
            return UIFont(name: "OpenSans", size: 40 / 2.000000)!
        }
        public class var fillColor: UIColor {
            return UIColorFromRGB(0xFFFFFF)
        }
    }

    // LayerTextStyle: "UI: TableView Pull To Load Label"
    public class uiTableViewPullToLoadLabel {
        public class var font: UIFont {
            return UIFont(name: "OpenSans-Light", size: 34 / 2.000000)!
        }
        public class var textColor: UIColor {
            return UIColor(red: 0.513725, green: 0.513725, blue: 0.513725, alpha: 1.000000)
        }
    }

}
