// File: StyleKitExport.swift
//
// NOTE:
// File automatically generated by "SketchStyleKitExport.php" tool.
// Any modification will lost on next export!

import UIKit

func UIColorFromRGB(hex: Int) -> UIColor {
    let R = CGFloat((hex & 0xFF0000) >> 16) / 255.0
    let G = CGFloat((hex & 0xFF00) >> 8) / 255.0
    let B = CGFloat(hex & 0xFF) / 255.0
    return UIColor(red: R, green: G, blue: B, alpha: 1.0)
}

public class StyleKitExport {
    
    // LayerStyle: "Icon: Background"
    public class iconBackground {
        public class var fillColor: UIColor {
            return UIColorFromRGB(0x44D3C2)
        }
    }

    // LayerStyle: "ProfileView: Avatar Outline"
    public class profileViewAvatarOutline {
        public class var borderColor: UIColor {
            return UIColorFromRGB(0xFFFFFF)
        }
    }

    // LayerStyle: "UI: Popup"
    public class uiPopup {
        public class var fillColor: UIColor {
            return UIColor(red: 68 / 255.0, green: 211 / 255.0, blue: 194 / 255.0, alpha: 0.89)
        }
    }

    // LayerStyle: "UI: Selected TableViewCell Background"
    public class uiSelectedTableViewCellBackground {
        public class var fillColor: UIColor {
            return UIColorFromRGB(0xF2F2F2)
        }
    }

    // LayerStyle: "UI: TableView Background"
    public class uiTableViewBackground {
        public class var fillColor: UIColor {
            return UIColorFromRGB(0xF9F9F9)
        }
    }

    // LayerTextStyle: "Post: Date"
    public class postDate {
        public class var font: UIFont {
            return UIFont(name: "OpenSans", size: 22 / 2.000000)!
        }
        public class var textColor: UIColor {
            return UIColor(red: 0.271518, green: 0.707377, blue: 0.655574, alpha: 1.000000)
        }
    }

    // LayerTextStyle: "Post: Title"
    public class postTitle {
        public class var font: UIFont {
            return UIFont(name: "OpenSans", size: 26 / 2.000000)!
        }
        public class var textColor: UIColor {
            return UIColor(red: 0.258238, green: 0.258238, blue: 0.258238, alpha: 1.000000)
        }
    }

    // LayerTextStyle: "UI: TableView Pull To Load Label"
    public class uiTableViewPullToLoadLabel {
        public class var font: UIFont {
            return UIFont(name: "OpenSans-Light", size: 34 / 2.000000)!
        }
        public class var textColor: UIColor {
            return UIColor(red: 0.513725, green: 0.513725, blue: 0.513725, alpha: 1.000000)
        }
    }

}
